default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  user: burgermap_admin
  password: burgermap_password
  host: localhost

development:
  <<: *default
  database: burgermap_development

test:
  <<: *default
  database: burgermap_test


production:
  <<: *default
  database: burgermap_production
  password: <%= ENV['BURGERMAP_DB_PASSWORD']>
